[[redirects]]
  from = "https://pdf.code-reading.org/*"
  to = "https://pdf.codereading.club/:splat"
  status = 301
  force = true

[build]
  publish = "public"
  functions = "functions"

[[plugins]]
package = "@netlify/plugin-functions-install-core"
